name: Docker Runner

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Build Container
        run: podman-compose -f docker-compose.yml build
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}

      - name: Stop Container
        run: podman-compose -f docker-compose.yml down
        
      - name: Run Container
        run: |
          podman-compose -f docker-compose.yml up -d
          docker ps --format '{{.Names}}' > containername
          sleep 5
          docker logs $(cat containername)
          hostname
          uname -a
          env > /tmp/github.env
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}


      - name: Cleanup Unused Images and Containers
        run: docker system prune -f
